apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.application.name }}-static-external-ip
  labels: {{- include "release.labels" . | nindent 4 }}
spec:
  rules:
    {{- range $ingressRule := .Values.ingress }}
    - http:
        paths:
          - path: {{ $ingressRule.path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ template "release.fullname" $ }}-http-{{ $ingressRule.componentName }}-service
                port:
                  name: http
    {{- end }}
  
